.PHONY: all

all:
	sudo apt install -qq net-tools -y
	sudo apt install -qq speedtest-cli -y
	sudo apt install -qq nload -y
	@echo Dependencies installed....
	@echo You can now start up CyberShield.....